### ISSUE TITLE
enable to add custom styles

### ISSUE THREAD

**Issue by AlwaniAnis** [mikeham98/react-awesome-calendar#3]

**Comment by Ammshath1997** [comment]
Hi,
I just started to work with this npm package so I don't know much about enable style but you can override the classes of the calendar,
in that also you can't change some of the default styles like change the daycell height because it is giving me an error. ( I'm using this package with next js)
 I have changed some of the styles to make the calendar small
![image](https://user-images.githubusercontent.com/55485418/122525563-fb6d7c80-d036-11eb-8786-ada6c7f5188c.png)

**Comment by adityasreeram007** [comment]
you can add it using ref.

**Comment by mikeham98** [comment]
I would recommend overriding the styles by having a custom stylesheet that overrides the classes. Or alternatively, you could modify it using the ref.
